version: "3.5"
name: "super-productive-services"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: super-productive-app
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/super-productive?schema=public
      - DIRECT_URL=postgresql://postgres:password@db:5432/super-productive?schema=public
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=your-secret-key
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next

  db:
    image: "postgres"
    restart: always
    container_name: super-productive-db
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "super-productive"
      POSTGRES_PASSWORD: password
    volumes:
      - database-data:/var/lib/postgresql-data/
    ports:
      - 8010:5432

volumes:
  database-data:
